version: '3.7'

services:

  ui:
    container_name: ui
    build:
      context: https://github.com/Sander-N/wrd-counter-ui.git#main:wrd-counter
      dockerfile: Dockerfile
    volumes:
      - '.:/wrd-counter'
      - '/wrd-counter/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true